version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    depends_on:
      - redis
      - db
    volumes:
      - ./logs:/app/logs
    networks:
      - agent-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: agent_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agent-network

  telegram-bot:
    build: .
    command: python -m src.connectors.telegram.bot
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    depends_on:
      - redis
      - db
    networks:
      - agent-network

  threads-bot:
    build: .
    command: python -m src.connectors.threads.bot
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    depends_on:
      - redis
      - db
    networks:
      - agent-network

volumes:
  redis_data:
  postgres_data:

networks:
  agent-network:
    driver: bridge 